const https = require("https");

exports.handler = async function(event) {
  const h = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "Content-Type",
    "Access-Control-Allow-Methods": "POST, OPTIONS"
  };
  if (event.httpMethod === "OPTIONS") return { statusCode: 200, headers: h, body: "" };

  function req(opts, body) {
    return new Promise(function(res, rej) {
      var r = https.request(opts, function(response) {
        var d = "";
        response.on("data", function(c) { d += c; });
        response.on("end", function() { res({ status: response.statusCode, body: d }); });
      });
      r.on("error", rej);
      if (body) r.write(body);
      r.end();
    });
  }

  try {
    var data = JSON.parse(event.body);
    var token = data.token;

    if (data.action === "get_deals") {
      var result = await req({
        hostname: "www.zohoapis.com",
        path: "/crm/v3/Deals?per_page=200&page=" + (data.page || 1) + "&fields=Deal_Name,Account_Name,Stage,Amount,Description,Owner,Closing_Date",
        method: "GET",
        headers: { "Authorization": "Zoho-oauthtoken " + token }
      });
      return { statusCode: result.status, headers: h, body: result.body };
    }

    if (data.action === "save_note") {
      var note = data.note_content + "\n\n--------------------\nGenerated by CapStone - Calibrations & Controls\nFull report: https://BJWCAC.github.io/fieldpro/FieldPro.html";
      var payload = JSON.stringify({ data: [{ Note_Title: data.note_title, Note_Content: note, Parent_Id: data.deal_id, se_module: "Deals" }] });
      var result2 = await req({
        hostname: "www.zohoapis.com",
        path: "/crm/v3/Deals/" + data.deal_id + "/Notes",
        method: "POST",
        headers: { "Authorization": "Zoho-oauthtoken " + token, "Content-Type": "application/json", "Content-Length": Buffer.byteLength(payload) }
      }, payload);
      return { statusCode: result2.status, headers: h, body: result2.body };
    }

    if (data.action === "refresh_token") {
      var result3 = await req({
        hostname: "accounts.zoho.com",
        path: "/oauth/v2/token?refresh_token=" + data.refresh_token + "&client_id=" + data.client_id + "&client_secret=" + data.client_secret + "&grant_type=refresh_token",
        method: "POST",
        headers: { "Content-Length": "0" }
      });
      return { statusCode: result3.status, headers: h, body: result3.body };
    }

    if (data.action === "upload_photo") {
      var imgBuf = Buffer.from(data.image_b64, "base64");
      var boundary = "CapStoneBound" + Date.now();
      var hdr = Buffer.from("--" + boundary + "\r\nContent-Disposition: form-data; name=\"file\"; filename=\"" + data.filename + "\"\r\nContent-Type: image/jpeg\r\n\r\n");
      var ftr = Buffer.from("\r\n--" + boundary + "--\r\n");
      var uploadBody = Buffer.concat([hdr, imgBuf, ftr]);
      var result4 = await req({
        hostname: "www.zohoapis.com",
        path: "/crm/v3/Deals/" + data.deal_id + "/Attachments",
        method: "POST",
        headers: {
          "Authorization": "Zoho-oauthtoken " + token,
          "Content-Type": "multipart/form-data; boundary=" + boundary,
          "Content-Length": uploadBody.length
        }
      }, uploadBody);
      return { statusCode: result4.status, headers: h, body: result4.body };
    }

    if (data.action === "workdrive_find_or_create_folder") {
      var listResult = await req({
        hostname: "www.zohoapis.com",
        path: "/workdrive/api/v1/files/" + data.parent_id + "/files?page[limit]=100",
        method: "GET",
        headers: {
          "Authorization": "Zoho-oauthtoken " + token,
          "Accept": "application/vnd.api+json"
        }
      });

      if (listResult.status >= 200 && listResult.status < 300) {
        try {
          var listData = JSON.parse(listResult.body);
          var target = (data.folder_name || "").toLowerCase().trim();
          var found = (listData.data || []).find(function(item) {
            var a = item.attributes || {};
            var isFolder = (a.is_folder === true) || (a.type === "folder") || (a.resource_type === "folder");
            var name = (a.name || a.display_name || "").toLowerCase().trim();
            return isFolder && name === target;
          });
          if (found) {
            return { statusCode: 200, headers: h, body: JSON.stringify({ folder_id: found.id, created: false }) };
          }
        } catch (e) {}
      } else {
        return { statusCode: listResult.status, headers: h, body: listResult.body };
      }

      var createBody = JSON.stringify({
        data: {
          attributes: { name: data.folder_name, parent_id: data.parent_id },
          type: "files"
        }
      });
      var createResult = await req({
        hostname: "www.zohoapis.com",
        path: "/workdrive/api/v1/files",
        method: "POST",
        headers: {
          "Authorization": "Zoho-oauthtoken " + token,
          "Content-Type": "application/vnd.api+json",
          "Accept": "application/vnd.api+json",
          "Content-Length": Buffer.byteLength(createBody)
        }
      }, createBody);

      if (createResult.status >= 200 && createResult.status < 300) {
        try {
          var created = JSON.parse(createResult.body);
          var newId = (created.data && created.data.id) || null;
          if (newId) {
            return { statusCode: 200, headers: h, body: JSON.stringify({ folder_id: newId, created: true }) };
          }
        } catch (e) {}
      }
      return { statusCode: createResult.status, headers: h, body: createResult.body };
    }

    if (data.action === "workdrive_upload") {
      var fileBuffer = Buffer.from(data.file_b64, "base64");
      var boundary = "CapStoneBound" + Date.now();
      var hdr = Buffer.from("--" + boundary + "\r\nContent-Disposition: form-data; name=\"content\"; filename=\"" + data.filename + "\"\r\nContent-Type: " + data.mime_type + "\r\n\r\n");
      var ftr = Buffer.from("\r\n--" + boundary + "--\r\n");
      var uploadBody = Buffer.concat([hdr, fileBuffer, ftr]);
      var result5 = await req({
        hostname: "www.zohoapis.com",
        path: "/workdrive/api/v1/files?parent_id=" + data.folder_id,
        method: "POST",
        headers: {
          "Authorization": "Zoho-oauthtoken " + token,
          "Content-Type": "multipart/form-data; boundary=" + boundary,
          "Content-Length": uploadBody.length
        }
      }, uploadBody);
      return { statusCode: result5.status, headers: h, body: result5.body };
    }

    return { statusCode: 400, headers: h, body: JSON.stringify({ error: "Unknown action" }) };

  } catch (err) {
    return { statusCode: 500, headers: h, body: JSON.stringify({ error: err.message }) };
  }
};
