const https = require("https");

exports.handler = async function(event) {
  const h = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "Content-Type",
    "Access-Control-Allow-Methods": "POST, OPTIONS"
  };
  if (event.httpMethod === "OPTIONS") return { statusCode: 200, headers: h, body: "" };

  function req(opts, body) {
    return new Promise(function(res, rej) {
      var r = https.request(opts, function(response) {
        var d = "";
        response.on("data", function(c) { d += c; });
        response.on("end", function() { res({ status: response.statusCode, body: d }); });
      });
      r.on("error", rej);
      if (body) r.write(body);
      r.end();
    });
  }

  try {
    var data = JSON.parse(event.body);
    var token = data.token;

    if (data.action === "get_deals") {
      var result = await req({
        hostname: "www.zohoapis.com",
        path: "/crm/v3/Deals?per_page=200&page=" + (data.page || 1) + "&fields=Deal_Name,Account_Name,Stage,Amount,Description,Owner,Closing_Date",
        method: "GET",
        headers: { "Authorization": "Zoho-oauthtoken " + token }
      });
      return { statusCode: result.status, headers: h, body: result.body };
    }

    if (data.action === "save_note") {
      var note = data.note_content;
      if (note.indexOf("Generated by CapStone") < 0) {
        note += "\n\n--------------------\nGenerated by CapStone - Calibrations & Controls";
      }
      var payload = JSON.stringify({ data: [{ Note_Title: data.note_title, Note_Content: note, Parent_Id: data.deal_id, se_module: "Deals" }] });
      var result2 = await req({
        hostname: "www.zohoapis.com",
        path: "/crm/v3/Deals/" + data.deal_id + "/Notes",
        method: "POST",
        headers: { "Authorization": "Zoho-oauthtoken " + token, "Content-Type": "application/json", "Content-Length": Buffer.byteLength(payload) }
      }, payload);
      return { statusCode: result2.status, headers: h, body: result2.body };
    }

    if (data.action === "find_note") {
      var findResult = await req({
        hostname: "www.zohoapis.com",
        path: "/crm/v3/Deals/" + data.deal_id + "/Notes?per_page=200&fields=Note_Title,Note_Content,Created_Time",
        method: "GET",
        headers: { "Authorization": "Zoho-oauthtoken " + token }
      });
      if (findResult.status < 200 || findResult.status >= 300) {
        return { statusCode: findResult.status, headers: h, body: findResult.body };
      }
      var found = null;
      try {
        var notes = (JSON.parse(findResult.body).data || []);
        for (var ni = 0; ni < notes.length; ni++) {
          var note = notes[ni];
          var content = String(note.Note_Content || "");
          if (data.marker && content.indexOf(data.marker) >= 0) { found = note; break; }
          if (!data.marker && !found && data.note_title && note.Note_Title === data.note_title) found = note;
        }
      } catch (ne) {}
      return { statusCode: 200, headers: h, body: JSON.stringify({ ok: true, note_id: found && found.id || null }) };
    }

    if (data.action === "update_note") {
      var updatedNote = data.note_content;
      if (updatedNote.indexOf("Generated by CapStone") < 0) {
        updatedNote += "\n\n--------------------\nGenerated by CapStone - Calibrations & Controls";
      }
      var updatePayload = JSON.stringify({ data: [{ Note_Title: data.note_title, Note_Content: updatedNote }] });
      var updateResult = await req({
        hostname: "www.zohoapis.com",
        path: "/crm/v3/Notes/" + data.note_id,
        method: "PUT",
        headers: { "Authorization": "Zoho-oauthtoken " + token, "Content-Type": "application/json", "Content-Length": Buffer.byteLength(updatePayload) }
      }, updatePayload);
      return { statusCode: updateResult.status, headers: h, body: updateResult.body };
    }

    if (data.action === "refresh_token") {
      var result3 = await req({
        hostname: "accounts.zoho.com",
        path: "/oauth/v2/token?refresh_token=" + data.refresh_token + "&client_id=" + data.client_id + "&client_secret=" + data.client_secret + "&grant_type=refresh_token",
        method: "POST",
        headers: { "Content-Length": "0" }
      });
      return { statusCode: result3.status, headers: h, body: result3.body };
    }

    if (data.action === "upload_photo") {
      var imgBuf = Buffer.from(data.image_b64, "base64");
      var boundary = "CapStoneBound" + Date.now();
      var hdr = Buffer.from("--" + boundary + "\r\nContent-Disposition: form-data; name=\"file\"; filename=\"" + data.filename + "\"\r\nContent-Type: image/jpeg\r\n\r\n");
      var ftr = Buffer.from("\r\n--" + boundary + "--\r\n");
      var uploadBody = Buffer.concat([hdr, imgBuf, ftr]);
      var result4 = await req({
        hostname: "www.zohoapis.com",
        path: "/crm/v3/Deals/" + data.deal_id + "/Attachments",
        method: "POST",
        headers: {
          "Authorization": "Zoho-oauthtoken " + token,
          "Content-Type": "multipart/form-data; boundary=" + boundary,
          "Content-Length": uploadBody.length
        }
      }, uploadBody);
      return { statusCode: result4.status, headers: h, body: result4.body };
    }

    if (data.action === "create_equipment") {
      var equipmentPayload = JSON.stringify({ data: [data.equipment || {}] });
      var equipmentResult = await req({
        hostname: "www.zohoapis.com",
        path: "/crm/v3/Equipments",
        method: "POST",
        headers: { "Authorization": "Zoho-oauthtoken " + token, "Content-Type": "application/json", "Content-Length": Buffer.byteLength(equipmentPayload) }
      }, equipmentPayload);
      return { statusCode: equipmentResult.status, headers: h, body: equipmentResult.body };
    }

    if (data.action === "upload_equipment_photo") {
      var assetImgBuf = Buffer.from(data.image_b64, "base64");
      var assetBoundary = "CapStoneBound" + Date.now();
      var assetHdr = Buffer.from("--" + assetBoundary + "\r\nContent-Disposition: form-data; name=\"file\"; filename=\"" + data.filename + "\"\r\nContent-Type: image/jpeg\r\n\r\n");
      var assetFtr = Buffer.from("\r\n--" + assetBoundary + "--\r\n");
      var assetUploadBody = Buffer.concat([assetHdr, assetImgBuf, assetFtr]);
      var assetUploadResult = await req({
        hostname: "www.zohoapis.com",
        path: "/crm/v3/Equipments/" + data.equipment_id + "/Attachments",
        method: "POST",
        headers: {
          "Authorization": "Zoho-oauthtoken " + token,
          "Content-Type": "multipart/form-data; boundary=" + assetBoundary,
          "Content-Length": assetUploadBody.length
        }
      }, assetUploadBody);
      return { statusCode: assetUploadResult.status, headers: h, body: assetUploadResult.body };
    }

    if (data.action === "workdrive_get_or_create_folder") {
      var parentId = data.parent_id || "";
      var folderName = String(data.folder_name || "Deal").substring(0, 120);
      var wantName = folderName.trim();
      var wdHeaders = {
        "Authorization": "Zoho-oauthtoken " + token,
        "Accept": "application/vnd.api+json"
      };
      var apiBases = [
        { host: "workdrive.zoho.com", prefix: "/api/v1" },
        { host: "www.zohoapis.com", prefix: "/workdrive/api/v1" }
      ];
      var debug = { list: [], create: [] };

      function folderUrl(id, attrs) {
        attrs = attrs || {};
        return attrs.permalink || attrs.web_url || ("https://workdrive.zoho.com/folder/" + id);
      }

      function parseFolderId(obj) {
        if (!obj) return null;
        if (obj.id && obj.id !== parentId) return obj.id;
        var d = obj.data;
        if (!d) return null;
        if (Array.isArray(d)) {
          var rec = d[0] || {};
          var rid = rec.id || (rec.attributes && (rec.attributes.resource_id || rec.attributes.id)) || null;
          return rid && rid !== parentId ? rid : null;
        }
        var rid2 = d.id || (d.attributes && (d.attributes.resource_id || d.attributes.id)) || null;
        return rid2 && rid2 !== parentId ? rid2 : null;
      }

      function isFolderItem(item) {
        var attrs = item.attributes || {};
        return attrs.is_folder === true || attrs.type === "folder" || attrs.resource_type === 1001;
      }

      function findInList(body) {
        try {
          var listed = JSON.parse(body);
          var items = listed.data || [];
          for (var li = 0; li < items.length; li++) {
            if (!isFolderItem(items[li])) continue;
            var attrs = items[li].attributes || {};
            var n = (attrs.name || attrs.display_html_name || "").trim();
            if (n === wantName) {
              var existingId = items[li].id || attrs.resource_id || attrs.id || null;
              if (existingId && existingId !== parentId) {
                return { id: existingId, url: folderUrl(existingId, attrs) };
              }
            }
          }
        } catch (e) {}
        return null;
      }

      function fallbackBody(reason) {
        return JSON.stringify({
          ok: false,
          folder_id: parentId,
          folder_url: "https://workdrive.zoho.com/folder/" + parentId,
          fallback: true,
          reason: reason || "unknown",
          debug: debug
        });
      }

      function successBody(hit, created) {
        return JSON.stringify({
          ok: true,
          folder_id: hit.id,
          folder_url: hit.url,
          created: !!created
        });
      }

      try {
        if (!parentId || !folderName) {
          return { statusCode: 200, headers: h, body: fallbackBody("missing parent or name") };
        }

        for (var bi = 0; bi < apiBases.length; bi++) {
          var base = apiBases[bi];
          var listPaths = [
            base.prefix + "/files/" + encodeURIComponent(parentId) + "/files?page[limit]=200",
            base.prefix + "/files/" + encodeURIComponent(parentId) + "/folders?page[limit]=200",
            base.prefix + "/teamfolders/" + encodeURIComponent(parentId) + "/folders?page[limit]=200"
          ];
          for (var pi = 0; pi < listPaths.length; pi++) {
            var listResult = await req({
              hostname: base.host,
              path: listPaths[pi],
              method: "GET",
              headers: wdHeaders
            });
            debug.list.push({ host: base.host, path: listPaths[pi], status: listResult.status });
            if (listResult.status >= 200 && listResult.status < 300) {
              var hit = findInList(listResult.body);
              if (hit) {
                return { statusCode: 200, headers: h, body: successBody(hit, false) };
              }
            }
          }
        }

        var createBodies = [
          JSON.stringify({ data: { attributes: { name: folderName, parent_id: parentId }, type: "files" } }),
          JSON.stringify({ data: { attributes: { name: folderName, parent_id: parentId, type: "folder" }, type: "files" } })
        ];
        for (var cbi = 0; cbi < apiBases.length; cbi++) {
          var cbase = apiBases[cbi];
          for (var cpi = 0; cpi < createBodies.length; cpi++) {
            var createPayload = createBodies[cpi];
            var createResult = await req({
              hostname: cbase.host,
              path: cbase.prefix + "/files",
              method: "POST",
              headers: Object.assign({}, wdHeaders, {
                "Content-Type": "application/json",
                "Content-Length": Buffer.byteLength(createPayload)
              })
            }, createPayload);
            debug.create.push({
              host: cbase.host,
              variant: cpi,
              status: createResult.status,
              body: String(createResult.body || "").substring(0, 160)
            });
            if (createResult.status >= 200 && createResult.status < 300) {
              try {
                var created = JSON.parse(createResult.body);
                var newId = parseFolderId(created);
                var cattrs = (created.data && !Array.isArray(created.data) && created.data.attributes) ||
                  (created.data && created.data[0] && created.data[0].attributes) || {};
                if (newId) {
                  return {
                    statusCode: 200,
                    headers: h,
                    body: successBody({ id: newId, url: folderUrl(newId, cattrs) }, true)
                  };
                }
              } catch (ce) {}
            }
          }
        }
      } catch (fe) {
        debug.error = fe.message;
      }
      return { statusCode: 200, headers: h, body: fallbackBody("list and create failed") };
    }

    if (data.action === "workdrive_upload") {
      var fileBuffer = Buffer.from(data.file_b64, "base64");
      var boundary = "CapStoneBound" + Date.now();
      var parentPart = Buffer.from("--" + boundary + "\r\nContent-Disposition: form-data; name=\"parent_id\"\r\n\r\n" + data.folder_id + "\r\n");
      var namePart = Buffer.from("--" + boundary + "\r\nContent-Disposition: form-data; name=\"filename\"\r\n\r\n" + data.filename + "\r\n");
      var overridePart = Buffer.from("--" + boundary + "\r\nContent-Disposition: form-data; name=\"override-name-exist\"\r\n\r\ntrue\r\n");
      var filePart = Buffer.from("--" + boundary + "\r\nContent-Disposition: form-data; name=\"content\"; filename=\"" + data.filename + "\"\r\nContent-Type: " + data.mime_type + "\r\n\r\n");
      var endPart = Buffer.from("\r\n--" + boundary + "--\r\n");
      var uploadBody = Buffer.concat([parentPart, namePart, overridePart, filePart, fileBuffer, endPart]);
      var result5 = await req({
        hostname: "www.zohoapis.com",
        path: "/workdrive/api/v1/upload",
        method: "POST",
        headers: {
          "Authorization": "Zoho-oauthtoken " + token,
          "Content-Type": "multipart/form-data; boundary=" + boundary,
          "Content-Length": uploadBody.length
        }
      }, uploadBody);
      if (result5.status >= 200 && result5.status < 300) {
        try {
          var parsed = JSON.parse(result5.body);
          var rec = (parsed.data && parsed.data[0]) || {};
          var attrs = rec.attributes || {};
          var rid = attrs.resource_id || rec.id || null;
          if (!rid && attrs["File INFO"]) {
            try { var fi = JSON.parse(attrs["File INFO"]); rid = fi.RESOURCE_ID || rid; } catch (e2) {}
          }
          var link = attrs.permalink || attrs.download_url || attrs.web_url || attrs.url ||
            (rid ? "https://workdrive.zoho.com/file/" + rid : null);
          return { statusCode: 200, headers: h, body: JSON.stringify({ ok: true, resource_id: rid, link: link }) };
        } catch (e3) {}
      }
      return { statusCode: result5.status, headers: h, body: result5.body };
    }

    return { statusCode: 400, headers: h, body: JSON.stringify({ error: "Unknown action" }) };

  } catch (err) {
    return { statusCode: 500, headers: h, body: JSON.stringify({ error: err.message }) };
  }
};
