const https = require("https");

exports.handler = async function(event) {
  const h = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "Content-Type",
    "Access-Control-Allow-Methods": "POST, OPTIONS"
  };
  if (event.httpMethod === "OPTIONS") return { statusCode: 200, headers: h, body: "" };

  function req(opts, body) {
    return new Promise(function(res, rej) {
      var r = https.request(opts, function(response) {
        var d = "";
        response.on("data", function(c) { d += c; });
        response.on("end", function() { res({ status: response.statusCode, body: d }); });
      });
      r.on("error", rej);
      if (body) r.write(body);
      r.end();
    });
  }

  try {
    var data = JSON.parse(event.body);
    var token = data.token;

    if (data.action === "get_deals") {
      var result = await req({
        hostname: "www.zohoapis.com",
        path: "/crm/v3/Deals?per_page=200&page=" + (data.page || 1) + "&fields=Deal_Name,Account_Name,Stage,Amount,Description,Owner,Closing_Date",
        method: "GET",
        headers: { "Authorization": "Zoho-oauthtoken " + token }
      });
      return { statusCode: result.status, headers: h, body: result.body };
    }

    if (data.action === "save_note") {
      var note = data.note_content + "\n\n--------------------\nGenerated by CapStone - Calibrations & Controls\nFull report: https://BJWCAC.github.io/fieldpro/FieldPro.html";
      var payload = JSON.stringify({ data: [{ Note_Title: data.note_title, Note_Content: note, Parent_Id: data.deal_id, se_module: "Deals" }] });
      var result2 = await req({
        hostname: "www.zohoapis.com",
        path: "/crm/v3/Deals/" + data.deal_id + "/Notes",
        method: "POST",
        headers: { "Authorization": "Zoho-oauthtoken " + token, "Content-Type": "application/json", "Content-Length": Buffer.byteLength(payload) }
      }, payload);
      return { statusCode: result2.status, headers: h, body: result2.body };
    }

    if (data.action === "refresh_token") {
      var result3 = await req({
        hostname: "accounts.zoho.com",
        path: "/oauth/v2/token?refresh_token=" + data.refresh_token + "&client_id=" + data.client_id + "&client_secret=" + data.client_secret + "&grant_type=refresh_token",
        method: "POST",
        headers: { "Content-Length": "0" }
      });
      return { statusCode: result3.status, headers: h, body: result3.body };
    }

    if (data.action === "upload_photo") {
      var imgBuf = Buffer.from(data.image_b64, "base64");
      var boundary = "CapStoneBound" + Date.now();
      var hdr = Buffer.from("--" + boundary + "\r\nContent-Disposition: form-data; name=\"file\"; filename=\"" + data.filename + "\"\r\nContent-Type: image/jpeg\r\n\r\n");
      var ftr = Buffer.from("\r\n--" + boundary + "--\r\n");
      var uploadBody = Buffer.concat([hdr, imgBuf, ftr]);
      var result4 = await req({
        hostname: "www.zohoapis.com",
        path: "/crm/v3/Deals/" + data.deal_id + "/Attachments",
        method: "POST",
        headers: {
          "Authorization": "Zoho-oauthtoken " + token,
          "Content-Type": "multipart/form-data; boundary=" + boundary,
          "Content-Length": uploadBody.length
        }
      }, uploadBody);
      return { statusCode: result4.status, headers: h, body: result4.body };
    }

    if (data.action === "workdrive_upload") {
      var fileBuffer = Buffer.from(data.file_b64, "base64");
      var boundary = "CapStoneBound" + Date.now();
      var parentPart = Buffer.from("--" + boundary + "\r\nContent-Disposition: form-data; name=\"parent_id\"\r\n\r\n" + data.folder_id + "\r\n");
      var namePart = Buffer.from("--" + boundary + "\r\nContent-Disposition: form-data; name=\"filename\"\r\n\r\n" + data.filename + "\r\n");
      var overridePart = Buffer.from("--" + boundary + "\r\nContent-Disposition: form-data; name=\"override-name-exist\"\r\n\r\ntrue\r\n");
      var filePart = Buffer.from("--" + boundary + "\r\nContent-Disposition: form-data; name=\"content\"; filename=\"" + data.filename + "\"\r\nContent-Type: " + data.mime_type + "\r\n\r\n");
      var endPart = Buffer.from("\r\n--" + boundary + "--\r\n");
      var uploadBody = Buffer.concat([parentPart, namePart, overridePart, filePart, fileBuffer, endPart]);
      var result5 = await req({
        hostname: "www.zohoapis.com",
        path: "/workdrive/api/v1/upload",
        method: "POST",
        headers: {
          "Authorization": "Zoho-oauthtoken " + token,
          "Content-Type": "multipart/form-data; boundary=" + boundary,
          "Content-Length": uploadBody.length
        }
      }, uploadBody);
      if (result5.status >= 200 && result5.status < 300) {
        try {
          var parsed = JSON.parse(result5.body);
          var rec = (parsed.data && parsed.data[0]) || {};
          var attrs = rec.attributes || {};
          var rid = attrs.resource_id || rec.id || null;
          if (!rid && attrs["File INFO"]) {
            try { var fi = JSON.parse(attrs["File INFO"]); rid = fi.RESOURCE_ID || rid; } catch (e2) {}
          }
          var link = attrs.permalink || attrs.download_url || attrs.web_url || attrs.url ||
            (rid ? "https://workdrive.zoho.com/file/" + rid : null);
          return { statusCode: 200, headers: h, body: JSON.stringify({ ok: true, resource_id: rid, link: link }) };
        } catch (e3) {}
      }
      return { statusCode: result5.status, headers: h, body: result5.body };
    }

    return { statusCode: 400, headers: h, body: JSON.stringify({ error: "Unknown action" }) };

  } catch (err) {
    return { statusCode: 500, headers: h, body: JSON.stringify({ error: err.message }) };
  }
};
